spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forum?characterEncoding=utf8&useSSL=false
    username: root
    password: jianpan
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080